WHENEVER SQLERROR EXIT SQL.SQLCODE
SET SERVEROUTPUT ON SIZE 400000
SET FEEDBACK OFF
SET VERIFY OFF

VAR ERR_CODE VARCHAR2(10);
VAR ERR_MSG VARCHAR2(200);

DECLARE
ERROR_PKG EXCEPTION;
BEGIN
NULL;
SIEBEL.XPKG_IB_VISTAS.SP_PRC_ACTUALIZA_CONTACTO(&1);
IF :ERR_CODE <> '000' THEN
   RAISE ERROR_PKG;
END IF;
EXCEPTION
WHEN OTHERS THEN
RAISE_APPLICATION_ERROR(-20001,:ERR_CODE||' '||:ERR_MSG);
END;
/

PRINT ERR_CODE;
PRINT ERR_MSG;

EXIT
